# ansible-playbook -i inventory playbook.yaml

- name: Ansible k8s
  remote_user: ansible
  tasks:
    - name: 開啟控制平面必要端口
      hosts: master
      firewalld:
        port: "{{item}}"
        permanent: yes
        state: disabled
        immediate: yes
        zone: public
      loop:
        - 6443/tcp
        - 2379-2380/tcp
        - 10250/tcp
        - 10259/tcp
        - 10257/tcp

    - name: 開啟工作節點必要端口
      hosts: worker
      firewalld:
        port: "{{item}}"
        permanent: yes
        state: disabled
        immediate: yes
        zone: public
      loop:
        - 10250/tcp
        - 30000-32767/tcp
    - name: Remove k8s.conf from modules-load.d
      ansible.builtin.file:
        path: /etc/modules-load.d/k8s.conf
        state: absent

    - name: Remove k8s.conf from sysctl.d
      ansible.builtin.file:
        path: /etc/sysctl.d/k8s.conf
        state: absent

    - name: Reload sysctl settings
      ansible.builtin.command:
        cmd: sysctl --system







